-- Log de la acción "Actualizar base" para mostrar "Última actualización" (día, hora Argentina, usuario).
-- Ejecutar en Supabase SQL Editor después de supabase_seguridad.sql.

CREATE TABLE IF NOT EXISTS public.log_actualizacion_base (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  at timestamptz NOT NULL DEFAULT now(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE SET NULL,
  user_email text
);

CREATE INDEX IF NOT EXISTS idx_log_actualizacion_base_at ON public.log_actualizacion_base (at DESC);

COMMENT ON TABLE public.log_actualizacion_base IS 'Registro cada vez que alguien ejecuta Actualizar base (upload Excel).';

-- RLS: solo quien tiene upload_base puede insertar; cualquier autenticado puede leer (para la leyenda).
ALTER TABLE public.log_actualizacion_base ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "log_actualizacion_base_insert_upload" ON public.log_actualizacion_base;
CREATE POLICY "log_actualizacion_base_insert_upload"
  ON public.log_actualizacion_base FOR INSERT TO authenticated
  WITH CHECK (public.has_permission('upload_base'));

DROP POLICY IF EXISTS "log_actualizacion_base_select_authenticated" ON public.log_actualizacion_base;
CREATE POLICY "log_actualizacion_base_select_authenticated"
  ON public.log_actualizacion_base FOR SELECT TO authenticated
  USING (true);

GRANT SELECT, INSERT ON public.log_actualizacion_base TO authenticated;

-- Registrar una actualización (usa el usuario actual y su email desde user_profiles).
CREATE OR REPLACE FUNCTION public.log_actualizacion_base()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  IF NOT public.has_permission('upload_base') THEN
    RAISE EXCEPTION 'Sin permiso para registrar actualización de base';
  END IF;
  INSERT INTO public.log_actualizacion_base (user_id, user_email)
  SELECT auth.uid(), COALESCE(p.email, '')
  FROM public.user_profiles p
  WHERE p.id = auth.uid();
END;
$$;

GRANT EXECUTE ON FUNCTION public.log_actualizacion_base() TO authenticated;

COMMENT ON FUNCTION public.log_actualizacion_base() IS 'Registra en log que el usuario actual ejecutó Actualizar base. Solo quien tiene upload_base.';
